# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Noise
tagline:          ''
description:      ''
url:              http://b225ccc.github.io
baseurl:          /

author:
  name:           'Brian Talley'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/b225ccc
