# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Noise
tagline:          ''
description:      ''
url:              http://b225ccc.github.io
baseurl:          /

author:
  name:           'Brian Talley'
  disqus-shortname: b225ccc

paginate:         5

# Custom vars
version:          2.1.0
gems:
  - jekyll-paginate
  - jekyll-gist

github:
  repo:           https://github.com/b225ccc
